# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: roomtorent
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: room-to-rent
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api
frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  stage: dev
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin


functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
